In [45]:
import pandas as pd
import os
from faker import Faker
import random
from sqlalchemy import create_engine

# Initialize Faker
fake = Faker()

In [46]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /home/danylozdoryk/Documents/real-time-e-commerce-sales-analytics/venv/lib/python3.11/site-packages (2.9.9)

## Generate some fake data

### Customers

In [47]:
num_customers = 100000

customers_data = []
for _ in range(num_customers):
    name = fake.name()
    address = fake.street_address()
    city = fake.city()
    postal_code = fake.postcode()
    country = fake.country()
    last_updated = fake.date_time_between(start_date='-1y', end_date='now')
    registration_date = fake.date_between(start_date='-5y', end_date='now')
    
    customers_data.append({
        'name': name,
        'address': address,
        'city': city,
        'postal_code': postal_code,
        'country': country,
        'last_updated': last_updated,
        'registration_date': registration_date
    })

# Create DataFrame
df_customers = pd.DataFrame(customers_data)

## Suppliers

In [48]:
num_suppliers = 150 

suppliers_data = []
for _ in range(num_suppliers):
    name = fake.company()
    address = fake.street_address()
    city = fake.city()
    postal_code = fake.postcode()
    country = fake.country()
    phone_number = fake.phone_number()
    
    suppliers_data.append({
        'name': name,
        'address': address,
        'city': city,
        'postal_code': postal_code,
        'country': country,
        'phone_number': phone_number
    })

# Create DataFrame
df_suppliers = pd.DataFrame(suppliers_data)

## Shippers

In [49]:
num_shippers = 20

shippers_data = []
for _ in range(num_shippers):
    name = fake.company()
    phone_number = fake.phone_number()
    
    shippers_data.append({
        'name': name,
        'phone_number': phone_number
    })

# Create DataFrame
df_shippers = pd.DataFrame(shippers_data)

## Read all files as df

In [50]:
# Read the csv files
folder = 'raw_data'

file_names = os.listdir(folder)
df = pd.concat([pd.read_csv(folder + f'/{file_name}') for file_name in file_names if file_name.endswith('.csv')])
df

,category,subcategory,name,current_price,raw_price,currency,discount,likes_count,is_new,brand,...,variation_0_color,variation_1_color,variation_0_thumbnail,variation_0_image,variation_1_thumbnail,variation_1_image,image_url,url,id,model
0,shoes,Mocassins,Chaussures décontractées antidérapantes en tis...,36.40,72.80,USD,50,873,False,NaN,...,Black,Khaki,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/flats-3616/p-1687903.html,1687903,SKUF29428
1,shoes,Mocassins,Chaussures en cuir à carreaux pour hommes de g...,46.36,106.49,USD,57,358,False,NaN,...,Red,Blue,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/flats-3616/p-1533324.html,1533324,SKUC99128
2,shoes,Mocassins,Chaussures décontractées en cuir pour hommes,43.38,119.98,USD,64,1511,False,Menico,...,Black,Khaki,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/-menico-flats-3616/p-16...,1651734,SKUE68011
3,shoes,Sneakers & Baskets,Baskets plates élastiques en tricot d'épissage,19.99,39.99,USD,50,1873,False,NaN,...,Green,Blue,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/sneakersandathletic-359...,1591892,SKUD85085
4,shoes,Mocassins,Hommes Cuir Épissage Soft Semelle Casual Chaus...,46.18,119.98,USD,62,2738,False,NaN,...,Bleu,Noir,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/flats-3616/p-1474682.html,1474682,SKUC15622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10203,men,Gilets,Gilets chauds d'extérieur élégants de couleur ...,54.99,81.99,USD,33,176,False,NaN,...,rouge,Noir,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/vests-4973/p-1214450.html,1214450,SKU788804
10204,men,Shirts,Chemises décontractées à rayures,17.99,33.99,USD,47,24,False,NaN,...,blanc,Noir,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/shirts-12209/p-1660726....,1660726,SKUE72114
10205,men,Shirts,Chemises à manches courtes à imprimé ours en p...,25.29,37.71,USD,33,84,False,NaN,...,#01,NaN,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,NaN,NaN,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/shirts-12209/p-1661284....,1661284,SKUE74270
10206,men,Shirts,Chemises imprimées ethniques pour hommes,23.09,33.94,USD,32,82,False,NaN,...,Blue,NaN,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,NaN,NaN,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/shirts-12209/p-1666391....,1666391,SKUE92625
10207,men,Shorts de bain,Plus Taille Deux Tortues De Mer Imprimé Deux P...,31.35,52.81,USD,41,38,False,ChArmkpR,...,Blue,NaN,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,NaN,NaN,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/charmkpr-board-shorts-6...,1669217,SKUE66551

## Create unique int id for categories table

In [51]:
category_to_id = {category: i + 1 for i, category in enumerate(df['category'].unique())}

df['category_id'] = df['category'].map(category_to_id)
df

,category,subcategory,name,current_price,raw_price,currency,discount,likes_count,is_new,brand,...,variation_1_color,variation_0_thumbnail,variation_0_image,variation_1_thumbnail,variation_1_image,image_url,url,id,model,category_id
0,shoes,Mocassins,Chaussures décontractées antidérapantes en tis...,36.40,72.80,USD,50,873,False,NaN,...,Khaki,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/flats-3616/p-1687903.html,1687903,SKUF29428,1
1,shoes,Mocassins,Chaussures en cuir à carreaux pour hommes de g...,46.36,106.49,USD,57,358,False,NaN,...,Blue,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/flats-3616/p-1533324.html,1533324,SKUC99128,1
2,shoes,Mocassins,Chaussures décontractées en cuir pour hommes,43.38,119.98,USD,64,1511,False,Menico,...,Khaki,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/-menico-flats-3616/p-16...,1651734,SKUE68011,1
3,shoes,Sneakers & Baskets,Baskets plates élastiques en tricot d'épissage,19.99,39.99,USD,50,1873,False,NaN,...,Blue,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/sneakersandathletic-359...,1591892,SKUD85085,1
4,shoes,Mocassins,Hommes Cuir Épissage Soft Semelle Casual Chaus...,46.18,119.98,USD,62,2738,False,NaN,...,Noir,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/flats-3616/p-1474682.html,1474682,SKUC15622,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10203,men,Gilets,Gilets chauds d'extérieur élégants de couleur ...,54.99,81.99,USD,33,176,False,NaN,...,Noir,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/vests-4973/p-1214450.html,1214450,SKU788804,9
10204,men,Shirts,Chemises décontractées à rayures,17.99,33.99,USD,47,24,False,NaN,...,Noir,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/shirts-12209/p-1660726....,1660726,SKUE72114,9
10205,men,Shirts,Chemises à manches courtes à imprimé ours en p...,25.29,37.71,USD,33,84,False,NaN,...,NaN,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,NaN,NaN,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/shirts-12209/p-1661284....,1661284,SKUE74270,9
10206,men,Shirts,Chemises imprimées ethniques pour hommes,23.09,33.94,USD,32,82,False,NaN,...,NaN,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,NaN,NaN,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/shirts-12209/p-1666391....,1666391,SKUE92625,9
10207,men,Shorts de bain,Plus Taille Deux Tortues De Mer Imprimé Deux P...,31.35,52.81,USD,41,38,False,ChArmkpR,...,NaN,https://imgaz1.chiccdn.com/thumb/list_grid/oau...,https://imgaz1.chiccdn.com/thumb/view/oaupload...,NaN,NaN,https://imgaz1.chiccdn.com/thumb/view/oaupload...,https://fr.newchic.com/charmkpr-board-shorts-6...,1669217,SKUE66551,9

## Create categories df

In [55]:
columns_to_select = ['category_id', 'category']
categories_df = df[columns_to_select].drop_duplicates(columns_to_select)
categories_df.rename(columns={'category_id': 'id', 'category': 'name'}, inplace=True)
categories_df['description'] = categories_df['name']
categories_df['image_url'] = 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nationalgeographic.com%2Fanimals%2Fmammals%2Ffacts%2Fdomestic-cat&psig=AOvVaw3Uz0J9pnLJA9E0maBnFVr0&ust=1716227417597000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKCe_72jmoYDFQAAAAAdAAAAABAE'
categories_df

,id,name,description,image_url
0,1,shoes,shoes,https://www.google.com/url?sa=i&url=https%3A%2...
0,2,jewelry,jewelry,https://www.google.com/url?sa=i&url=https%3A%2...
0,3,accessories,accessories,https://www.google.com/url?sa=i&url=https%3A%2...
0,4,kids,kids,https://www.google.com/url?sa=i&url=https%3A%2...
0,5,beauty,beauty,https://www.google.com/url?sa=i&url=https%3A%2...
0,6,women,women,https://www.google.com/url?sa=i&url=https%3A%2...
0,7,house,house,https://www.google.com/url?sa=i&url=https%3A%2...
0,8,bags,bags,https://www.google.com/url?sa=i&url=https%3A%2...
0,9,men,men,https://www.google.com/url?sa=i&url=https%3A%2...

## Create Products df

In [64]:
columns_to_select = ['name', 'category_id', 'subcategory','variation_0_color',  'current_price']
products_df = df[columns_to_select].drop_duplicates(columns_to_select)
products_df.rename(columns={'variation_0_color': 'description', 'current_price': 'price'}, inplace=True)

products_df['stock_qty'] = [random.randint(10, 1500) for _ in range(len(products_df))]
products_df['supplier_id'] = [random.randint(1, 150) for _ in range(len(products_df))]
products_df

,name,category_id,subcategory,description,price,stock_qty,supplier_id
0,Chaussures décontractées antidérapantes en tis...,1,Mocassins,Black,36.40,903,42
1,Chaussures en cuir à carreaux pour hommes de g...,1,Mocassins,Red,46.36,352,94
2,Chaussures décontractées en cuir pour hommes,1,Mocassins,Black,43.38,1226,115
3,Baskets plates élastiques en tricot d'épissage,1,Sneakers & Baskets,Green,19.99,1114,4
4,Hommes Cuir Épissage Soft Semelle Casual Chaus...,1,Mocassins,Bleu,46.18,343,51
...,...,...,...,...,...,...,...
10203,Gilets chauds d'extérieur élégants de couleur ...,9,Gilets,rouge,54.99,792,126
10204,Chemises décontractées à rayures,9,Shirts,blanc,17.99,21,33
10205,Chemises à manches courtes à imprimé ours en p...,9,Shirts,#01,25.29,1012,109
10206,Chemises imprimées ethniques pour hommes,9,Shirts,Blue,23.09,715,87
10207,Plus Taille Deux Tortues De Mer Imprimé Deux P...,9,Shorts de bain,Blue,31.35,569,64

## Insert data

In [66]:
# Establish a connection to the PostgreSQL database
engine = create_engine('postgresql://postgres:1234@localhost:5432/postgres')

# Write the DataFrame to the database
categories_df.to_sql(name='categories', con=engine, if_exists='truncate', index=False)
df_customers.to_sql(name='customers', con=engine, if_exists='append', index=False)
df_shippers.to_sql(name='shippers', con=engine, if_exists='append', index=False)
df_suppliers.to_sql(name='suppliers', con=engine, if_exists='append', index=False)
products_df.to_sql(name='products', con=engine, if_exists='append', index=False)

# Close the connection
engine.dispose()

ValueError: 'truncate' is not valid for if_exists